### ISSUE TITLE
Squeak-ev list info missing

### ISSUE THREAD

**Issue by krono** [squeak-smalltalk/squeak.de#2]
A link to the squeak-ev list at http://lists.squeakfoundation.org/cgi-bin/mailman/listinfo/squeak-ev would be helpful

**Comment by fniephaus** [comment]
Where would you put this link?

**Comment by krono** [comment]
(that's the actual question here ;))

**Comment by fniephaus** [comment]
_Squeak e.V._ > _Mailingliste_?

**Comment by fniephaus** [comment]
I added a mail icon to the footer, also the link has already been available at:
http://squeak.de/squeakev/#informationen-zur-mitgliedschaft
